spring:
  jms:
    pub-sub-domain: false
    listener:
      destination-name: DEV.QUEUE.1
      concurrency: 1
      max-concurrency: 5
ibm.mq:
  host: 127.0.0.1
  port: 1414
  queueManager: QM1
  channel: DEV.APP.SVRCONN
  queue: MY_QUEUE
  connName: localhost(1414)
  user: admin
  password: passw0rd
